[package]
name = "iu-canister"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[dependencies]
serde = { version = "1.0.188", features = ["derive"] }
serde_json = "1.0.66"
serde_bytes = "0.11"
serde_cbor = "0.11"
candid.workspace = true
hex = "0.4.3"
ic-cdk = "0.13"
ic-certified-map = "0.4.0"
url = "2.4.1"
time = { version = "0.3.30", features = ["formatting"] }
rand_chacha = { version = "0.3.1", optional = true }
getrandom = { version = "0.2.10", features = ["custom"] }
k256 = "0.13.2"
tiny-keccak = { version = "2.0.2", features = ["keccak"] }
sha2 = "0.9.1"
simple_asn1 = "0.6.2"
ic_siwe = {version = "0.0.6", git="https://github.com/hackartists/ic-siwe.git", branch="main" }
ic-stable-structures = "0.6.4"
dto.workspace = true
ic-cdk-timers = "0.8.0"
ethabi = "18.0.0"
