[package]
name = "main-ui"
version = "0.2.0"
authors.workspace = true
description.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
reqwest.workspace = true
dto.workspace = true
dioxus = { workspace = true, features = ["router", "web", "fullstack"] }
by-components.workspace = true
dioxus-oauth.workspace = true
google-wallet.workspace = true
dioxus-translate.workspace = true
dioxus-popup.workspace = true
rest-api.workspace = true
by-macros.workspace = true

dioxus-aws.workspace = true
dioxus-web.workspace = true
dioxus-logger = { version = "0.5.0" }
tracing = { version = "0.1.40" }

wasm-bindgen = { version = "0.2.100", optional = true }
wasm-bindgen-futures = { version = "0.4.50", optional = true }
web-sys = { version = "0.3.72", features=["Navigator"]}
serde = "1.0.216"
num-format = "0.4.4"

chrono = "0.4.39"
base64 = "0.22.1"
url = "2.5.4"

[features]
default = []
web = ["dioxus-aws/web", "dioxus-translate/web", "wasm-bindgen", "wasm-bindgen-futures"]
server = ["dioxus-aws/server"]
lambda = ["server", "dioxus-aws/lambda"]